### PR TITLE
Rebase dekn#8065

### PR DESCRIPTION
**Pull request by agateaux**
To address https://github.com/plotly/dekn/issues/8065

### CODE REVIEW

**Comment by agateaux** [comment]
No more critical of high CVE:

```
cnb/buildpacks/paketo-buildpacks_poetry/5.4.0/bin/run (gobinary)
================================================================
Total: 7 (UNKNOWN: 2, LOW: 0, MEDIUM: 5, HIGH: 0, CRITICAL: 0)
```

**Review by BRONSOLO — APPROVED** [review]
🚀

**Comment by BRONSOLO** [comment]
I'll create the 5.4 release branch again off of main once this lands. No need for the backport PR.

**Comment by agateaux** [comment]
@tarzzz Maybe a 2nd look to this one as well, on the toml file.

**Pull request merged**
